#pragma once

#define WM_TL_MESSAGE_BASE			(WM_USER + (0x0080))

#define WM_TL_OPT_PLAY_START		(WM_TL_MESSAGE_BASE+1)
#define WM_TL_OPT_PLAY_STOP			(WM_TL_MESSAGE_BASE+2)
#define WM_TL_OPT_PLAY_PAUSE		(WM_TL_MESSAGE_BASE+3)
#define WM_TL_OPT_PLAY_RESUME		(WM_TL_MESSAGE_BASE+4)
#define WM_TL_OPT_PLAY_TOGGLE_PAUSE	(WM_TL_MESSAGE_BASE+5)

#define WM_TL_UPDATE_DISPLAY		(WM_TL_MESSAGE_BASE+10)

#define WM_TL_PLAY_TIME_UPDATE		(WM_TL_MESSAGE_BASE+11)
#define WM_TL_PLAY_OPENING_MEDIA	(WM_TL_MESSAGE_BASE+12)
#define WM_TL_PLAY_STARTED			(WM_TL_MESSAGE_BASE+13)
#define WM_TL_PLAY_STOPED			(WM_TL_MESSAGE_BASE+14)
#define WM_TL_PLAY_PAUSED			(WM_TL_MESSAGE_BASE+15)
#define WM_TL_PLAY_TO_END			(WM_TL_MESSAGE_BASE+16)

#define WM_TL_VOLUME_CHANGED		(WM_TL_MESSAGE_BASE+17)
#define WM_TL_AUDIO_CHANGED			(WM_TL_MESSAGE_BASE+18)
#define WM_TL_VIDEO_CHANGED			(WM_TL_MESSAGE_BASE+19)

#define WM_TL_PLAY_EXIT_FULL_SCREEN			(WM_TL_MESSAGE_BASE+20)

#define WM_TL_PLAY_SCREEN_MODE_CHANGED		(WM_TL_MESSAGE_BASE+21)

#define WM_TL_PLAY_VIEW_PORT_ON_DCLICK		(WM_TL_MESSAGE_BASE+22)