

#define TL_RESOURCE_BASE			800

//#define IDD_TL_VIEWWINDOW			TL_RESOURCE_BASE+1
//#define IDD_TL_VIEWPORT				TL_RESOURCE_BASE+2
#define IDD_STATIC_PLAYING_TIME		TL_RESOURCE_BASE+3
#define IDD_STATIC_PLAY_STATUS		TL_RESOURCE_BASE+4


#define IDD_STATIC_VIEWPORT_TAG_BASE	TL_RESOURCE_BASE+6
#define IDD_STATIC_VIEWPORT_TAG_0		IDD_STATIC_VIEWPORT_TAG_BASE
#define IDD_STATIC_VIEWPORT_TAG_1		TL_RESOURCE_BASE+7
#define IDD_STATIC_VIEWPORT_TAG_2		TL_RESOURCE_BASE+8
#define IDD_STATIC_VIEWPORT_TAG_3		TL_RESOURCE_BASE+9